//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repventas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Repventas()
        {
            this.Clientes = new HashSet<Clientes>();
            this.Oficinas = new HashSet<Oficinas>();
            this.Pedidos = new HashSet<Pedidos>();
            this.Repventas1 = new HashSet<Repventas>();
        }
    
        public decimal num_empl { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> edad { get; set; }
        public Nullable<decimal> oficina_rep { get; set; }
        public string titulo { get; set; }
        public System.DateTime contrato { get; set; }
        public Nullable<decimal> director { get; set; }
        public Nullable<decimal> cuota { get; set; }
        public decimal ventas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clientes> Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oficinas> Oficinas { get; set; }
        public virtual Oficinas Oficinas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos> Pedidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repventas> Repventas1 { get; set; }
        public virtual Repventas Repventas2 { get; set; }
    }
}
